demo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mysite.views import index,login,resume,job
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'demo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$',login.login),
    url(r'^accounts/logout/$',login.logout),
    url(r'^accounts/signup/$',login.signup),

    url(r'^$',index.index),

    url(r'^myresume/$',resume.myresume),
    url(r'^myresume/work-experience/$',resume.experience,{'form_name':'w_form','model_name':'w_model'}),
    url(r'^myresume/study-experience/$',resume.experience,{'form_name':'s_form','model_name':'s_model'}),
    url(r'^myresume/image/$',resume.image),
    url(r'^search/resume/',resume.search_resume),
    url(r'^resume/(\d{1,5})/$',resume.resume_display),

    url(r'^search/job/',job.search_job),
    url(r'^mycompany/$',job.mycompany),
    url(r'^mycompany/job/$',job.job),
    url(r'^mycompany/alter/company/$',job.alter_info,{'info_type':'company','offset':None}),
    url(r'^mycompany/alter/job/(\d{1,5})/$',job.alter_info,{'info_type':'job'}),
    url(r'^job/(\d{1,5})/$',job.job_display),
    url(r'^job/apply/(\d{1,5})/$',job.job_apply_or_favorite,{'action_type':'apply_job'}),
    url(r'^job/favorite/(\d{1,5})/$',job.job_apply_or_favorite,{'action_type':'favorite_job'}),
    url(r'^job/feedback/$',job.job_feedback),
    url(r'^myjob/$',job.job_apply_favorite_record),
    url(r'^apply/feedback/(\d{1,5})/$',job.read_feedback),
)

mysite/forms.py
#coding:utf-8
from django import forms
from django.contrib.auth.models import User


error_messages = {
    'username':{
                'required': u'必须填写用户名',
                'max_length': u'用户名长度过长（3-12个字符）'
                },
    'email':{
            'required': u'必须填写E-mail',
            'max_length': u'Email长度有误',
            'invalid':u'请填写正确的邮箱地址'
            },
    'password': {
                'required': u'密码不能为空',
                'max_length': u'密码长度过长',
                'min_length':u'密码少于6个字符'
                },
    'date':{
            'invalid':u'日期格式不正确，正确格式：2015-1-1'

            },
    'text':{
            'max_length':u'文本长度超过最大值',
            'required':u'必须填写'
            },
    'image':{
            'empty':u'上传不能为空',
            'required':u'未选择任何照片'
            },
    'company_intfield':{
           'max_value':u'超过最大值100000',
           'min_value':u'人数不能小于0',
    },
    'job_intfield':{
           'max_value':u'超过最大值1000',
           'min_value':u'人数不能小于1',
    },
}

class Signup_form(forms.Form):
    username=forms.CharField(max_length=20,label=u"用户名",
        error_messages=error_messages.get('username'))
    password=forms.CharField(min_length=6,max_length=20,label=u'密码',widget=forms.PasswordInput,required=True,error_messages=error_messages.get('password'))
    repassword=forms.CharField(min_length=6,max_length=20,label=u'再次输入密码',widget=forms.PasswordInput,required=True,
        error_messages=error_messages.get('password'))
    email=forms.EmailField(max_length=20,label=u'邮箱',
        error_messages=error_messages.get('email'))
    identity=forms.BooleanField(label=u'注册为 HR?',initial=False,required=False)

    def clean_repassword(self):
        password=self.cleaned_data['password']
        repassword=self.cleaned_data['repassword']
        if  password != repassword:
            raise forms.ValidationError(u'密码不一致')
        return repassword
    def clean_username(self):
        username=self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError(u'用户名已被注册')
        return username

class Login_form(forms.Form):
    #required_css_class='form-control'
    username=forms.CharField(max_length=20,label=u"用户名",
        error_messages=error_messages.get('username'))
    password=forms.CharField(max_length=20,label=u'密码',widget=forms.PasswordInput,error_messages=error_messages.get('password'))

class Resume_form(forms.Form):
    name=forms.CharField(max_length=255,label=u'姓名')
    city=forms.CharField(max_length=255,required=False,label=u'现居城市')
    mobilephone=forms.CharField(max_length=11,required=False,label=u'手机号码')
    email=forms.EmailField(max_length=75,required=False,label=u'邮箱地址',error_messages=error_messages.get('email'))
    hope_work=forms.CharField(max_length=255,required=False,label=u'期望工作')
    hope_type=forms.CharField(max_length=255,required=False,label=u'工作类型：全职/实习')
    hope_city=forms.CharField(max_length=255,required=False,label=u'期望工作城市')
    hope_salary=forms.CharField(max_length=255,required=False,label=u'期望薪资')
    education=forms.CharField(max_length=255,required=False,label=u'学历')
    description=forms.CharField(max_length=255,required=False,label=u'自我描述',widget=forms.Textarea)
    self_evaluate=forms.CharField(max_length=255,required=False,label=u'自我评价',widget=forms.Textarea)
    tag=forms.CharField(max_length=255,required=False,label=u'个人亮点')

class Work_experience_form(forms.Form):
    key_id=forms.CharField(max_length=10,label=u'id',widget=forms.HiddenInput,required=False)
    company_name=forms.CharField(max_length=255,required=False,label=u'公司名称')
    start_date=forms.DateField(required=False,widget=forms.DateInput,label=u'起始日期',error_messages=error_messages.get('date'))
    end_date=forms.DateField(required=False,widget=forms.DateInput,label=u'结束日期',error_messages=error_messages.get('date'))
    job=forms.CharField(max_length=255,required=False,label=u'工作岗位')
    description=forms.CharField(required=False,label=u'工作内容',widget=forms.Textarea)

class Study_experience_form(forms.Form):
    key_id=forms.CharField(max_length=10,label=u'id',widget=forms.HiddenInput,required=False)
    school_name=forms.CharField(max_length=255,required=False,label=u'学校名称')
    start_date=forms.DateField(required=False,label=u'起始日期')
    end_date=forms.DateField(required=False,label=u'结束日期')
    educational=forms.CharField(max_length=255,required=False,label=u'学历')
    subject=forms.CharField(max_length=255,required=False,label=u'专业')

class Company_form(forms.Form):
    name=forms.CharField(max_length=255,label=u'公司名字',error_messages=error_messages.get('text'))
    city=forms.CharField(max_length=255,required=False,label=u'所在城市')
    stage=forms.CharField(max_length=255,required=False,label=u'阶段')
    tag=forms.CharField(max_length=255,required=False,label=u'标签')
    people_num=forms.IntegerField(max_value=100000,min_value=0,required=False,label=u'人数',error_messages=error_messages.get('company_intfield'))
    home_url=forms.CharField(max_length=255,required=False,label=u'公司网址')
    description=forms.CharField(required=False,label=u'公司简介',widget=forms.Textarea)

class Job_form(forms.Form):
    key_id=forms.CharField(max_length=10,required=False,label=u'id',widget=forms.HiddenInput)
    name=forms.CharField(max_length=255,required=False,label=u'职位名称')
    work_place=forms.CharField(max_length=255,required=False,label=u'工作地点')
    num=forms.IntegerField(min_value=1,max_value=1000,required=False,label=u'招聘人数',error_messages=error_messages.get('job_intfield'))
    scal=forms.CharField(max_length=255,required=False,label=u'薪资')
    experience=forms.CharField(max_length=255,required=False,label=u'工作经验')
    educational=forms.CharField(max_length=255,required=False,label=u'学历')
    job_type=forms.CharField(max_length=255,required=False,label=u'工作类型：全职/实习')
    tag=forms.CharField(max_length=255,required=False,label=u'标签')
    description=forms.CharField(required=False,label=u'工作描述',widget=forms.Textarea)
    end_date=forms.DateField(required=False,label=u'过期时间',error_messages=error_messages.get('date'))

class Image_form(forms.Form):
    upimage=forms.ImageField(label=u'上传照片',error_messages=error_messages.get('image'))

    def clean_upimage(self):
        upimage=self.cleaned_data.get('upimage',False)
        if upimage:
            if upimage.size>2*1024*1024:
                raise ValidationError(u'上传照片超过2mb限制，请重新上传')
            else:
                return upimage
        else:
            raise ValidationError(u'上传失败')

class Feedback_form(forms.Form):
    key_id=forms.IntegerField(widget=forms.HiddenInput)
    user_id=forms.IntegerField(widget=forms.HiddenInput)
    job_id=forms.IntegerField(widget=forms.HiddenInput)
    content=forms.CharField(error_messages=error_messages.get('text'),widget=forms.Textarea,label=u'发送回执')

mysite/views/login.py
#coding:utf-8
from django.shortcuts import render_to_response
from django import template
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
from django.contrib import auth
from django.contrib.auth.models import User
from mysite.models import *
from mysite.forms import *
from mysite.utils import *

# Create your views here.
def login(request):
    if request.method == 'GET':
        t=template.loader.get_template('login.html')
        f=Login_form()
        c=template.RequestContext(request,{'form':f})
        html=t.render(c)
        return HttpResponse(html)
    else:
        query_str=request.META['QUERY_STRING']
        query_str=query_str if query_str !='' else 'next=/'
        next_path=extract_path_arg(query_str)['next']
        f=Login_form(request.POST)
        if f.is_valid():
            login_info=f.cleaned_data
            user=auth.authenticate(username=login_info['username'],password=login_info['password'])
            if user is not None and user.is_active:
                auth.login(request,user)
                return HttpResponseRedirect(next_path)
            else:
                t=template.loader.get_template('login.html')
                c=template.RequestContext(request,{'form':f,'login_error':1})
                html=t.render(c)
                return HttpResponse(html)
        else:
            t=template.loader.get_template('login.html')
            c=template.RequestContext(request,{'form':f})
            html=t.render(c)
            return HttpResponse(html)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')
def signup(request):
    if request.method == 'GET':
        t=template.loader.get_template('signup.html')
        f=Signup_form()
        print f['username'].label_tag
        c=template.RequestContext(request,{'form':f})
        html=t.render(c)
        return HttpResponse(html)
    else:
        f=Signup_form(request.POST)
        if f.is_valid():
            sign_info=f.cleaned_data
            user=User.objects.create_user(username=sign_info['username'],password=sign_info['password'],email=sign_info['email'])
            is_hr=Is_HR(user_id=user.id,is_hr=sign_info['identity'])
            is_hr.save()
            return HttpResponse('signup success')
        else:
            t=template.loader.get_template('signup.html')
            c=template.RequestContext(request,{'form':f})
            html=t.render(c)
            return HttpResponse(html)

templates/alter_info.html
{% include 'nav.html' %}

<div style="margin:0 auto;width:70%">
    <form method="post" action="{{ form_action_path }}" id="repost" >
    {% csrf_token %}
    {% load bootstrap %}

    {{ form|bootstrap }}

    <input class="btn btn-success" type="submit"   value="重新提交">

    </form>
</div>

{% include 'footer.html' %}

templates/feedback.html
{% include 'nav.html' %}
<div class="container">
<div style="margin:0 auto;width:70%">
    <h4>发送回执</h4>
    <form method="post" action="/job/feedback/">
    {% csrf_token %}
    <input id="id_key_id" name="key_id" type="hidden" value="{{ request.GET.key_id }}" />
    <input id="id_uid" name="user_id" type="hidden" value="{{ request.GET.user_id }}" />
    <input id="id_job_id" name="job_id" type="hidden" value="{{ request.GET.job_id }}" />
    <textarea class=" form-control" cols="40" id="id_content" name="content" rows="10"></textarea>
    <br>
    <input class="btn btn-success" type="submit"   value="提交">
    </form>
</div>
</div>
{% include 'footer.html' %}

templates/footer.html
<footer id="footer" >
    <hr>
    <div style="margin-left:3em">
    <p>2015 &copy;  <a href="#" >sumi</a> Powered By Django
        <br/>
        Email:sumi@163.com
    </p>
    </div>
</footer>
</body>
{% block css %}{% endblock %}
{% block script %}{% endblock %}
</html>

templates/index.html
{% include 'nav.html' %}
<div class="container theme-showcase" role="main">
<form class="form-inline" action="/search/job/" method="get" target="_blank">
      <div class="form-group">
        <label for="jobSearcher">职位搜索：</label>
        <input type="text" class="form-control" name="kw"  id="jobSearcher" placeholder="如：产品经理">
      </div>
      <button type="submit" class="btn btn-default">搜索</button>
    </form>
<br>
    <form class="form-inline" action="/search/resume" method="get" target="_blank">
      <div class="form-group">
        <label for="resumeSearcher">简历搜索：</label>
        <input type="text" class="form-control" name="kw" id="resumeSearcher" placeholder="期望职位如：高级运维">
      </div>
      <button type="submit" class="btn btn-default">搜索</button>
    </form>
<br><br>
<h4>用户概览</h4>
  <p>默认账号admin，密码admin</p>
{% for item in user %}
  <p>{{ forloop.counter }}===>{{ item.username}}-------Email：{{ item.email }}</p>
{% endfor %}
<br>
<h4>简历概览</h4>
{% for item in resume %}
  <p>{{ forloop.counter }}===>{{ item.name}}-------期望工作：{{ item.hope_work }}</p>
{% endfor %}
<br>
<h4>公司概览</h4>
{% for item in company %}
  <p>{{ forloop.counter }}===>{{ item.name }}-------标签：{{ item.tag }}</p>
{% endfor %}
<br>
<h4>职位概览</h4>
{% for item in job %}
  <p>{{ forloop.counter }}===>{{ item.name }}-------标签：{{ item.tag }}</p>
{% endfor %}
</div>
{% include 'footer.html' %}

templates/job_apply_favorite_record.html
{% include 'nav.html' %}

<div class="container">
<div class="panel panel-default" style="padding-left:2em;padding-top:1em">
<div class="panelbody" >
<h3>我的投递信息</h3>
{% for item in apply_job %}
{% if item.feedback_id %}
<p>{{ forloop.counter }}-----<a href="/job/{{ item.job_id }}/">{{ item.job_name }}</a>-----<a href="">{{ item.company_name }}</a>-----申请时间：{{ item.create_date|date:"Y-m-d" }}-----<a href="/apply/feedback/{{ item.feedback_id }}/" target="_blank">查看回执</a><sapn>-----接收日期：{{ item.feedback_date|date:"Y-m-d" }}</sapn>
{% if item.feedback_is_read %}
<sapn>-----状态：已读</sapn></p>
{% else %}
<sapn>-----状态：未读</sapn></p>
{% endif %}

{% else %}
<p>{{ forloop.counter }}-----<a href="/job/{{ item.job_id }}/?from=my_apply">{{ item.job_name }}</a>-----<a href="#">{{ item.company_name }}</a>-----<sapn>未有回执</span>-----投递日期：{{ item.job_create_date|date:"Y-m-d" }}

{% endif %}
{% endfor %}
</div>
</div>

<br><br>
<div class="panel panel-default" style="padding-left:2em;padding-top:1em">
<div class="panelbody" >
<h3>我的收藏</h3>
{% for item in favorite_job %}
<p>{{ forloop.counter }}-----<a href="/job/{{ item.job_id }}/?from=my_fav">{{ item.job_name }}</a>-----<a href="#">{{ item.company_name }}</a>-----+
{% endfor %}
</div>
</div>

</div>
<br><br>
{% include 'footer.html' %}

templates/job_display.html
{% include 'nav.html' %}

<div class="container">
<div class="" >
    <h4>{{ company.name }}</span></h4>
    <p><span style="margin-right:2em">所在城市：{{ company.city }}</span>
    <span style="margin-right:2em">阶段：{{ company.stage }}</span>
    <span style="margin-right:2em">人数：{{ company.people_num}}</span></p>
    <P><span>标签：{{ company.tag }}</span></P>
    <p><a href="http://{{ company.home_url }}">主页：{{ company.home_url }}</a></p>
    <p>公司简介：</p>
    <P style="margin-left:0">{{ company.description|linebreaksbr }}</p>
</div>

<div class="panel panel-default" style="padding-left:2em;padding-top:1em" id="job-{{ forloop.counter }}">
    <div class="panelbody" >

    <h5><span style="margin-right:2em">职位名：{{ job.name }}</span></h5>
    <p><span style="margin-right:2em">工作地点：{{ job.work_place }}</span>
    <span style="margin-right:2em">招聘人数：{{ job.num }}</span>
    <span style="margin-right:2em">薪资：{{ job.scal }}</span>
    <span>经验要求：{{ job.experience }}</span>
    <span style="margin-right:2em">学历：{{ job.educational }}</span>
    <span style="margin-right:2em">工作类型：全职/实习：{{ job.job_type }}</span></p>
    <p><span style="margin-right:2em">标签：{{ job.tag }}</span></p>
    <p>职位描述：</p>
    <P style="margin-left:0">{{ job.description|linebreaksbr }}</p>
    <p>过期时间：{{ job.end_date|date:"Y-m-d"  }}</p>
    <p>
    {% if from_page != "my_apply" %}
    <a href="/job/apply/{{ job.id }}/" target="_blank" style="margin-right:2em">申请职位</a>
    {% endif %}
    {% if from_page != "my_fav" %}
    <a href="/job/favorite/{{ job.id }}/" target="_blank">收藏职位</a>
    {% endif %}
    </p>
    </div>
    <br>
    </div>

{% include 'footer.html' %}

templates/login.html
<!DOCTYPE HTML>
<html>
<head>
<title>登陆</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
</style>
<link rel="stylesheet" href="http://127.0.0.1:85/static/bootstrap/css/bootstrap.min.css">
<link href="http://127.0.0.1:85/static/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
<link rel="stylesheet" href="http://127.0.0.1:85/static/css/style.css">
<script type="text/javascript" src="http://127.0.0.1:85/static/js/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="http://127.0.0.1:85/static/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://127.0.0.1:85/static/js/bin.js"></script>
</head>

<body>
<div style="margin:0 auto;width:300px">
<h2 style="margin-left:50px;margin-bottom:50px;">登陆</h2>
<form method="POST" action="/accounts/login/" id="login">
    {% csrf_token %}
    {% load bootstrap %}

    {{ form|bootstrap }}

    <input class="btn btn-success" type="button" onclick="changeAction()"  value="登陆">
    {% if login_error %}
        <p style="color:red">用户名或密码错误</p>
    {% endif %}
</form>
</div>

</body>
<script type="text/javascript">
    function changeAction()
    {
    var f=document.getElementById("login")
    f.action=window.location.href
    f.submit()
    }
</script>
</html>

templates/message.html
{% include 'nav.html' %}

<div class="container">
 <div class="jumbotron">
      <h3>{{ msg_subject }}</h3>
      <p>{{ msg_content }}</p>
</div>

</div>

{% include 'footer.html' %}

templates/mycompany.html
{% include 'nav.html' %}

<div class="container theme-showcase" role="main">
    {% if company %}
    <div class="" >
    <h4>{{ company.name }}</span></h4>
    <p><span style="margin-right:2em">所在城市：{{ company.city }}</span>
    <span style="margin-right:2em">阶段：{{ company.stage }}</span>
    <span style="margin-right:2em">人数：{{ company.people_num}}</span></p>
    <P><span>标签：{{ company.tag }}</span></P>
    <p><a href="http://{{ company.home_url }}">主页：{{ company.home_url }}</a></p>
    <p>公司简介：</p>
    <P style="margin-left:0">{{ company.description|linebreaksbr }}</p>
    <p><a href="/mycompany/alter/company/" target="_blank">修改公司信息</a></p>
    </div>

    <br><br>

    {% for item in job %}
    <div class="panel panel-default" style="padding-left:2em;padding-top:1em" id="job-{{ forloop.counter }}">
    <div class="panelbody" >
    <h5>{{ forloop.counter }}.</h5>
    <h5><span style="margin-right:2em">职位名：{{ item.name }}</span></h5>
    <p><span style="margin-right:2em">工作地点：{{ item.work_place }}</span>
    <span style="margin-right:2em">招聘人数：{{ item.num }}</span>
    <span style="margin-right:2em">薪资：{{ item.scal }}</span>
    <span>经验要求：{{ item.experience }}</span>
    <span style="margin-right:2em">学历：{{ item.educational }}</span>
    <span style="margin-right:2em">工作类型：全职/实习：{{ item.job_type }}</span></p>
    <p><span style="margin-right:2em">标签：{{ item.tag }}</span></p>
    <p>职位描述：</p>
    <P style="margin-left:0">{{ item.description|linebreaksbr }}</p>
    <p>过期时间：{{ item.end_date|date:"Y-m-d"  }}</p>
    <p><a href="/mycompany/alter/job/{{ item.id }}/" target="_blank">修改职位信息</a></p>
    <hr>
    <h5>职位申请信息</h5>
    {% for n in item.job_apply_info %}
    <p>{{ forloop.counter }}-----申请时间：{{ n.create_date|date:"Y-m-d" }}----<a href="/resume/{{ n.resume_id }}" target="_blank">查看简历</a>-----<a href="/job/feedback/?key_id={{ n.id }}&user_id={{ n.user_id }}&job_id={{ n.job_id }} " target="_blank">发送回执</a></p>
    {% endfor %}
    </div>
    <br>
    </div>
    {% endfor %}

    <br><br>
    <a class="btn btn-success" href="javascript:void(0);" onclick="$('#job').show();">创建招聘职位</a>
    <form method="post" id="job" action="/mycompany/job/" class="form" style="display:none;">
    {% csrf_token %}
    <div class="form-group"><label ></label>
    <input type="hidden" name="key_id" value="">
    </div>
    <div class="form-group"><label >职位名字</label>
    <input type="text" name="name" placeholder="name" class="form-control" >
    </div>
    <div class="form-group"><label >工作地点</label>
    <input type="text" name="work_place" placeholder="work place" class="form-control" >
    </div>
    <div class="form-group"><label >招聘人数</label>
    <input type="text" name="num" placeholder="num" class="form-control" >
    </div>
    <div class="form-group"><label >薪资</label>
    <input type="text" name="scal" placeholder="scal" class="form-control" >
    </div>
    <div class="form-group"><label >经验要求</label>
    <input type="text" name="experience" placeholder="experience" class="form-control" >
    </div>
    <div class="form-group"><label >学历</label>
    <input type="text" name="educational" placeholder="educational" class="form-control" >
    </div>
    <div class="form-group"><label >工作类型：全职/实习</label>
    <input type="text" name="job_type" placeholder="job_type" class="form-control" >
    </div>
    <div class="form-group"><label >标签</label>
    <input type="text" name="tag" placeholder="tag" class="form-control" >
    </div>
    <div class="form-group"><label >职位描述</label>
    <textarea rows="10" name="description" placeholder="description" class="form-control"></textarea>
    </div>
    <div class="form-group"><label >过期时间</label>
    <input type="text" name="end_date" placeholder="format:2015-1-1" class="form-control" >
    </div>
    <input class="btn btn-success" type="submit"   value="提交">
    </form>


    {% else %}
    <h2>尚未创建公司</h2>
    <a class="btn btn-success" href="javascript:void(0);" onclick="$('#company').show();">创建公司</a>
    <form method="post" id="company" action="/mycompany/" class="form" style="display:none;">
    {% csrf_token %}
    <div class="form-group"><label >公司名字</label>
    <input type="text" name="name" placeholder="name" class="form-control">
    </div>
    <div class="form-group"><label >所在城市</label>
    <input type="text" name="city" placeholder="city" class="form-control">
    </div>
    <div class="form-group"><label >阶段</label>
    <input type="text" name="stage" placeholder="stage" class="form-control" >
    </div>
    <div class="form-group"><label >标签</label>
    <input type="text" name="tag" placeholder="tag" class="form-control">
    </div>
    <div class="form-group"><label >人数</label>
    <input type="text" name="people_num" placeholder="people_num" class="form-control">
    </div>
    <div class="form-group"><label >网址</label>
    <input type="text" name="home_url" placeholder="home_url" class="form-control">
    </div>
    <div class="form-group"><label >简介</label>
    <textarea rows="10" name="description" placeholder="description" class="form-control"></textarea>
    </div>
    <input class="btn btn-success" type="submit"   value="提交">
    </form>
    {% endif %}
</div>
{% include 'footer.html' %}

templates/nav.html
<!DOCTYPE html>
<!-- saved from url=(0039)http://5.sumioo.sinaapp.com/index/index -->
<html lang="zh-CN"><head profile="http://gmpg.org/xfn/11"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>demo</title>
    <link rel="stylesheet" href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" >
<!--<link href="http://127.0.0.1:85/static/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">  -->
    <link rel="stylesheet" href="/static/css/style.css">
    <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/bin.js"></script>
    <!--[if IE]>
    <script src="/static/default/html5.js"></script>
    <![endif]-->
    <meta name="keywords" content="">
    <meta name="description" content="">
<script>window["_GOOG_TRANS_EXT_VER"] = "1";</script></head><style>#ads_c_tpc, .a_fl, .a_fr, .a_h, .a_mu, .a_pb, .a_pr, .a_pt, .ad_footerbanner, #ad_headerbanner, .ad_headerbanner, [id^="ad_thread"], .archiver_banne, .bm.a_c, .wp.a_f, #sitefocus.focus { display: none !important; }</style>
<body role="document" style="zoom: 1;">
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="http://5.sumioo.sinaapp.com/index/index#">拉勾项目</a>-->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">首页</a></li>
        <li><a href="/myresume/">我的简历</a></li>
        <li><a href="/myjob/">我的投递和收藏</a></li>
        <li><a href="/mycompany/">我的公司</a></li>
        {% if  request.user.is_authenticated %}
            <li><a href="">用户:{{ request.user.username }}</a></li>
            <li><a href="/accounts/logout">退出</a></li>
        {% else %}
            <li><a href="/accounts/login/">登陆</a></li>
            <li><a href="/accounts/signup/">注册</a></li>
        {% endif %}

        </ul>
        </li>
        </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>